status = [
  'playground-build (Node.js 12)',
  'playground-build (Node.js 14)',
  'integration-tests (Node.js 12)',
  'integration-tests (Node.js 14)',
  'style-check',
  'cypress-run'
]
# 1 hour timeout
timeout-sec = 3600
